import { NextRequest } from 'next/server';
import { hasOpenAIKey } from '@/lib/openai';
import { pickFallbackTea } from '@/lib/tea-fallback';
import { getCachedTodayFeed, type TeaCard as TeaFeedCard } from '@/lib/today-feed';
import { loadCards } from '@/lib/today-storage';

// CARD READ STRATEGY (stale-while-revalidate):
//   1. Try Vercel Blob first — always populated, always fast (~50ms cold, <10ms warm)
//   2. Fall through to unstable_cache if Blob is unavailable
//   3. Fall through to evergreen fallback if both fail (so iOS never sees an empty Tea tab)
//
// This means the cron's 30-second LLM rebuild NEVER blocks a user request.
// The cron writes to Blob atomically; users keep reading the previous day's
// cards until the swap completes. Zero cold-cache window.
async function readCards(): Promise<TeaFeedCard[]> {
  // Primary: Vercel Blob (instant, always populated)
  try {
    const stored = await loadCards();
    if (stored && stored.cards.length > 0) {
      return stored.cards;
    }
  } catch {
    // fall through
  }

  // Fallback: unstable_cache (will rebuild if cold — only happens when Blob is unconfigured)
  try {
    return await getCachedTodayFeed();
  } catch {
    return [];
  }
}

/**
 * GROUNDED LEGACY-FIELD SYNTHESIZER
 *
 * The legacy /api/today response shape (drama / players / lesson) used to be
 * generated by a free-form LLM call (`generateTea()`) that pulled storylines
 * from training-data memory. That generator HALLUCINATED specific games,
 * scores, dates, and opponents (e.g. inventing a "Wemby played the Lakers"
 * detail that never happened, or a Mahomes-vs-Chargers fictional Oct 22 game).
 *
 * Brand promise: never invent. Always cite. So we now synthesize the legacy
 * fields directly from the grounded `cards` feed:
 *   - drama: card[0]'s headline + body (real news, sourced from ESPN)
 *   - players: primaryPlayer of cards 0-3 (only players named in real news)
 *   - lesson: static evergreen, NOT generated
 *
 * The legacy `generateTea()` function has been deleted. Old iOS builds
 * showing the legacy hero will see the SAME content as the first card in
 * the new feed (redundant but accurate). Once Phase 2 (Rork Tea-tab redesign)
 * ships, the hero disappears entirely and only the new card list renders.
 */
function synthesizeLegacyFromCards(
  cards: TeaFeedCard[],
  league: 'nfl' | 'nba' | 'both'
): { drama: { prompt: string; response: string }; players: TodayResponse['players']; lesson: { title: string; body: string } } {
  // Pull lead card — prefer one matching the user's league preference if specified
  const filtered =
    league === 'both'
      ? cards
      : cards.filter((c) => c.league === league);
  const lead = filtered[0] || cards[0] || null;

  const drama = lead
    ? {
        prompt: lead.preview ? lead.preview.split('.')[0] + '?' : `What's the latest with ${lead.primaryPlayer?.name ?? 'today'}?`,
        response: lead.body,
      }
    : {
        prompt: "What's today's tea?",
        response: "Pull-to-refresh on the Tea tab to load today's Brew. New stories every morning.",
      };

  // Players carousel — pull primaryPlayers from up to 4 cards (real, named in real news)
  const seenPlayers = new Set<string>();
  const featured: TodayResponse['players'] = [];
  for (const c of cards) {
    if (!c.primaryPlayer) continue;
    if (seenPlayers.has(c.primaryPlayer.id)) continue;
    if (c.league === 'wnba') continue; // legacy field is typed nfl|nba only
    if (league !== 'both' && c.league !== league) continue;
    seenPlayers.add(c.primaryPlayer.id);
    featured.push({
      id: c.primaryPlayer.id,
      name: c.primaryPlayer.name,
      team: c.primaryPlayer.team,
      league: c.league as 'nfl' | 'nba',
      number: 0, // jersey numbers not on TeaFeedCard primaryPlayer; iOS-old-build doesn't critically depend on this
    });
    if (featured.length >= 4) break;
  }

  // Lesson is now a static evergreen — old iOS UI gets a stable nudge, no generation cost.
  const lesson = {
    title: "Today's Brew",
    body: "Eight to twelve fresh stories every morning, refreshed daily at 7am ET. Tap any card below for the full tea — sourced, dated, never invented.",
  };

  return { drama, players: featured, lesson };
}

/**
 * POST /api/today
 *
 * Generates the daily 3-card "Tea" payload for the mobile app's Tea tab AND
 * the post-paywall magic moment. Each call returns:
 *   - drama: a personalized lens-voiced 100-word response
 *   - players: 4 player thumbnails for "players to know this week"
 *   - lesson: a 60-second crash course
 *
 * Caches per (lens, league, ISO date) for 6 hours in memory to keep OpenAI
 * costs reasonable when many users share the same lens.
 *
 * Falls back to evergreen Tea pack if OPENAI_API_KEY missing OR generation fails.
 */

export const runtime = 'nodejs';

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Access-Control-Max-Age': '86400',
};

export async function OPTIONS() {
  return new Response(null, { status: 204, headers: CORS_HEADERS });
}

type RequestBody = {
  lens?: string;
  league?: 'nfl' | 'nba' | 'both';
  displayName?: string;
  vibeLevel?: 'clueless' | 'basics' | 'curious' | 'fan';
  lastSeenAt?: string;
};

type TodayResponse = {
  date: string; // YYYY-MM-DD
  drama: { prompt: string; response: string };
  players: { id: string; name: string; team: string; league: 'nfl' | 'nba'; number: number }[];
  lesson: { title: string; body: string };
  /**
   * NEW (2026-05): Multi-card Tea feed generated daily from live ESPN headlines.
   * 8-12 fresh cards rewritten in sportsBFF voice with tier/category tags.
   * Empty array if generation hasn't run yet today (falls back to drama+lesson).
   */
  cards?: TeaFeedCard[];
  cached?: boolean;
  fallback?: boolean;
};

// In-memory cache. Key: `${lens}|${league}|${YYYY-MM-DD}`. Value: TodayResponse.
// 6-hour TTL.
const CACHE_TTL_MS = 6 * 60 * 60 * 1000;
const _cache = new Map<string, { value: TodayResponse; expires: number }>();

function cacheKey(lens: string, league: string, date: string): string {
  return `${lens}|${league}|${date}`;
}

function isoDateUTC(): string {
  return new Date().toISOString().slice(0, 10);
}

// NOTE: The free-form generateTea() and pickFeaturedPlayers() functions used to live
// here. They've been deleted because the LLM was hallucinating specific games (scores,
// dates, opponents) that never happened — violating the brand promise "Never invent.
// Always cite." The legacy /api/today response shape is now synthesized from the
// grounded card feed via synthesizeLegacyFromCards() above.

export async function POST(req: NextRequest) {
  let body: RequestBody = {};
  try {
    body = (await req.json()) as RequestBody;
  } catch {
    // Empty body is OK — use defaults
  }

  const lens = body.lens || 'plain';
  const league = body.league || 'both';
  const displayName = body.displayName;
  const vibeLevel = body.vibeLevel;
  const today = isoDateUTC();

  // Pull the daily multi-card Tea feed in parallel with everything else.
  // Cached for 24h, invalidated by /api/cron/build-today.
  const cardsPromise = readCards().catch(() => [] as TeaFeedCard[]);

  // Cache check
  const key = cacheKey(lens, league, today);
  const cached = _cache.get(key);
  if (cached && cached.expires > Date.now()) {
    const cards = await cardsPromise;
    return new Response(
      JSON.stringify({ ...cached.value, cards, cached: true }),
      { status: 200, headers: { 'Content-Type': 'application/json', ...CORS_HEADERS } }
    );
  }

  // No API key → fallback
  if (!hasOpenAIKey()) {
    const fallback = pickFallbackTea(lens, league);
    const cards = await cardsPromise;
    const response: TodayResponse = {
      date: today,
      ...fallback,
      cards,
      fallback: true,
    };
    _cache.set(key, { value: response, expires: Date.now() + CACHE_TTL_MS });
    return new Response(JSON.stringify(response), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...CORS_HEADERS },
    });
  }

  // Synthesize the legacy drama/players/lesson fields from grounded cards.
  // No more free-form LLM hallucination — every claim ships sourced.
  try {
    const cards = await cardsPromise;

    if (cards.length === 0) {
      // No cards available — fall through to evergreen pack so old iOS UI doesn't crash
      const fallback = pickFallbackTea(lens, league);
      const response: TodayResponse = {
        date: today,
        ...fallback,
        cards,
        fallback: true,
      };
      _cache.set(key, { value: response, expires: Date.now() + CACHE_TTL_MS });
      return new Response(JSON.stringify(response), {
        status: 200,
        headers: { 'Content-Type': 'application/json', ...CORS_HEADERS },
      });
    }

    const synthesized = synthesizeLegacyFromCards(cards, league);
    const response: TodayResponse = {
      date: today,
      drama: synthesized.drama,
      players: synthesized.players,
      lesson: synthesized.lesson,
      cards,
    };
    _cache.set(key, { value: response, expires: Date.now() + CACHE_TTL_MS });
    return new Response(JSON.stringify(response), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'X-Today-Cards-Count': String(cards.length),
        'X-Today-Source': 'grounded-cards',
        ...CORS_HEADERS,
      },
    });
  } catch (err) {
    // Synthesis failed — graceful fallback to evergreen pack
    const fallback = pickFallbackTea(lens, league);
    const cards = await cardsPromise.catch(() => [] as TeaFeedCard[]);
    const response: TodayResponse = {
      date: today,
      ...fallback,
      cards,
      fallback: true,
    };
    return new Response(JSON.stringify(response), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'X-Today-Error': String(err).slice(0, 100),
        ...CORS_HEADERS,
      },
    });
  }
}

/**
 * GET /api/today — convenience endpoint returning JUST the new cards feed.
 * iOS Tea-tab v2 hits this directly when it only needs the multi-card list
 * (no lens-voiced drama/lesson). Reads from Blob with cache fallback —
 * effectively zero latency, never blocks on a cron rebuild.
 */
export async function GET() {
  const cards = await readCards().catch(() => [] as TeaFeedCard[]);
  return new Response(
    JSON.stringify({
      date: isoDateUTC(),
      cards,
      count: cards.length,
    }),
    {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'X-Today-Cards-Count': String(cards.length),
        'X-Today-Source': cards.length > 0 ? 'blob-or-cache' : 'empty',
        ...CORS_HEADERS,
      },
    }
  );
}
